const Data = [
   "Yesterday I saw a film titled Macbeth. Its story elements are interestin. The film's hero, Macbeth, assassinates Duncan and ascends to the throne of Scotland. But he is dissastisfied. He finds himself in a dangerous situation. He executes those he suspects of plotting against him. Eventurally, some of the lords revolted and dethroned him and killed him. The message it conveys is that excessive ambition destrous a man. The actore and actress who played Macbeth and Lady Macbeth had exceptional performances which significantly increased the film's impact.",
   "Since March 8, 1990, Women's Day has been observed by SAARC (South Asian Association for Regional Cooperation) comprising seven countries namely India, Pakistan, Nepal, Bhutan, Bangladesh, Sri Lanka and Maldives. The day is celebrated to highlight the problems of the girl child in these countries. It is very sad that girl children are subjected to extreme neglect and disrespect, especially in underdeveloped countries. The birth of a girl child is seen by parents as a cause of pity. They are deprived of proper nutrition, education, economic opportunities and social status or respect. We must eliminate these prejudices and provide a bright future for girls by educating them.",
   "Everyone knows that paper is made from trees. But when one looks at trees, one cannot imagine that something so soft and fragile as the paper is made it's so hard and strong. Plant materials such as wood are made of fibres known as cellulose. It is the primary ingredient in paper making.",
   "Gardening is my favourite Hobby, I own a small plot of land next to our house. I cultivate gardening there. Every day, I spend half an hour gardening. After returning from my morning walk, I go to my garden with a spade and a bucket of water. I prepare the soil, prune the plants, and water them. I also use insecticides and fertilisers. My heart leaps with joy when i see the plants swaying in the wind. I feel heavenly pleasure as i watch them grow day by day",
   "Home is the place where we return to rest after a day's work, and where parents and children meet together and have a carefree and jouful time. Our family consists of three members-father, mother, and brother. We live in a rural area. It is free from the hustle and bustle of city life. It is especiallly famous for its scenic beauty. I am the most important member of the family. Everyone trusts my judgement and agrees to follow my suggestions.",
   "The teacher of today is the salt of the earth. he wants to create a man, not just make money. He is a knowledgeable gentleman. He is an expert in the particular subject he teaches. Though a scholar, he teaches the subject in such a way that all students, brillint or ordinary, can fully understand him. He doesn't advertise his knowledge. He cares about his students and offers assistance to them both inside and outside of the classroom. He attends his work regularly."
]

export default Data;